apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: 902685116131.dkr.ecr.ap-south-1.amazonaws.com/shopeasy-backend
    newTag: 864c505cbc7e83e189b79f4d6a3c596e86e94dd1
  - name: 902685116131.dkr.ecr.ap-south-1.amazonaws.com/shopeasy-frontend
    newTag: 864c505cbc7e83e189b79f4d6a3c596e86e94dd1
